### ISSUE TITLE
Tracking bug: RBAC for KDE Plasma

### ISSUE THREAD

**Issue by secureworkstation** [wrabcak/selinux-policy-contrib#192]
I'm working on making RBAC work in KDE Plasma. This is a tracking bug for all the effort I make towards the goal.

Small PRs for selinux-policy-contrib:
- [ ] Fix for Pulseaudio https://github.com/fedora-selinux/selinux-policy-contrib/pull/191
- [ ] Label /run/user/.../bus correctly https://github.com/fedora-selinux/selinux-policy-contrib/pull/196
- [ ] Label /run/user/.../pulse/ correctly https://github.com/fedora-selinux/selinux-policy-contrib/pull/197

Small PRs for selinux-policy:
- [ ] Fix for ssh-agent eating logs https://github.com/fedora-selinux/selinux-policy/pull/316
- [x] Dontaudit for ptmx_t macro https://github.com/fedora-selinux/selinux-policy/pull/315
- [x] Label /usr/bin/fusermount3 https://github.com/fedora-selinux/selinux-policy/pull/317
- [ ] Pulseaudio & DBUS have correct labels in /run/user/.../ https://github.com/fedora-selinux/selinux-policy/pull/321

Transitioning for kwalletd5 (when launched by PAM):
- [x] Patch https://phabricator.kde.org/D26979?download=true
- [ ] Upstream (in progress) https://phabricator.kde.org/D26979
- [ ] Downstream

KDE Plasma policy:
- [x] Confinement for kdeconnect
- [x] Confinement for kwalletd5
- [ ] Main patchset prepared
- [ ] Main patchset merged

Overall:
- [x] KDE Plasma testable in RBAC enforcing
- [ ] Make a test suite
- [ ] KDE Plasma correctly working in RBAC enforcing

Related proposals:
- Labeling for wayland
- Labeling for session systemd

**Comment by secureworkstation** [comment]
Good news: it starts with 0 sealerts in RBAC enforcing :)
And same with gnome-shell running kdeconnect and kwallet on X11 on sddm.
And (almost) same with gnome-shell running both on X11 and Wayland on gdm.
And (almost) same with KDE Plasma on X11 on gdm.
